### ISSUE TITLE
TODO: User System / Playercards

### ISSUE THREAD

**Issue by JustCodiex** [BattlegroundsCoH/coh-battlegrounds#118]
**In Dashboard**
The dashboard will be the main view through which the user interacts with their user profile.

- [ ] Login/Register/Logout
- [ ] Profile Display
- [ ] Todo...

** In Company Builder**
The company builder will integrate more with the system -> stored on the server and more statistics are tracked. Achievements may also be earned and displayed as part of the profile.

- [ ] More company statistics
- [ ] Company achievements/medals
- [ ] Todo...

**In Lobby**
A simple popup window that will display basic information about the current player (wins, losses, kills/losses, most played company, most played faction, selected company info etc.)

- [ ] Popup on request
- [ ] Todo...

**Backend**
The backend support for handling users.

- [ ] User Management
- [ ] Todo...

**Note(s)**
*The user system should be entirely optional and not forced onto users who do not want it.*
*Convert most of the above to issues on their own once the time comes.*
