### ISSUE TITLE
TODO: CoH3 Support

### ISSUE THREAD

**Issue by JustCodiex** [BattlegroundsCoH/coh-battlegrounds#220]
- [x] Investigate if CoH3 is viable
- [x] Internal support for CoH3
- [x] Launcher support for CoH3
- [x] Replay Reader for CoH3
- [x] Gamemode compiler for CoH3
- [x] #221
